---
title: "Compte à rebours"

output: html_document
---

<style type="text/css">

h1.title {
font-size: 38px;
color: DarkRed;
text-align: center;
}

h1 {
font-size: 25px;
text-align: center;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
require(flipdownr)
require(htmltools)
```


```{r, echo=FALSE}
get_righ_year <- function(month, day) {
  if (as.numeric(format(Sys.Date(), "%m")) > month) {
    return(as.numeric(format(Sys.Date(), "%Y")) + 1) 
  } 
  else if ((as.numeric(format(Sys.Date(), "%m")) == month) & (as.numeric(format(Sys.Date(), "%d")) >= day)) {
    return(as.numeric(format(Sys.Date(), "%Y")) + 1)
  } 
  else {
    return(format(Sys.Date(), "%Y"))
  }
}
```

# Noël 🎅


```{r, echo = FALSE}
month = 12
day  = 25

year = get_righ_year(month, day)


div(flipdown(downto = paste(year, month, day, sep="-"), id = "Christmas"), align="center")
```

---

# Fin de l'école


```{r, echo = FALSE}

month = 01
day  = 22

year = get_righ_year(month, day)

div(flipdown(downto = paste(year, month, day, sep="-"), id = "End_School"), align="center")
```

---

# Déménagement


```{r, echo = FALSE}

month = 01
day  = 25

year = get_righ_year(month, day)

div(flipdown(downto = paste(year, month, day, sep="-"), id = "New_Life"), align="center")
```
